channels:
  - conda-forge

dependencies:
  - python=3.9
  - numpy=1.22.2
  - scipy>=1.8.0
  - matplotlib>=3.5.1
  - scikit-image>=0.19.2
  - scikit-video>=1.1.11
  - ffmpeg>=6.0.0
  - av>=10.0.0
  - pims>=0.6.1
